from Embeddings.Tfidf_Embedding.tfidf_embeddings import generate_tfidf_embeddings
from Embeddings.Word2Vec_Embeddings.word2vec_embeddings import generate_word2vec_embeddings
from Embeddings.Sbert_Embeddings.sbert_embeddings import generate_sbert_embeddings
from Embeddings.Bert_Embeddings.bert_embeddings import generate_bert_embeddings

# generate_tfidf_embeddings()
# generate_word2vec_embeddings()
# generate_sbert_embeddings()
generate_bert_embeddings()